
#include <iostream>
#include <cstring>
#include <cstdlib>
#include <stdio.h>
#include <stdlib.h>
#include "Clave.h"
#include "ElementoNodo.h"
#include "Atributo.h"
#include "AtributoFijo.h"
#include "AtributoVariable.h"
#include "Registro.h"
#include "Componente.h"
#include "Nodo.h"
#include "NodoHoja.h"
#include "NodoIntermedio.h"
#include "Clave.h"
#include "ComparadorClave.h"
#include "ComparadorPrueba.h"
#include "BSharpTree.h"
using namespace std;

int main() {
	cout << "BSharpTree" << endl;
	Referencia refAux;
	bool encontrado;
	ComparadorClave* comparador = new ComparadorPrueba();
	AtributoFijo<char*> nombre("nombre",15);
	AtributoFijo<int> dni("dni");
    int numero=1;
    char unNombre[15]="abaco";
    nombre.set(unNombre);
    dni.set(&numero);
	Registro reg(2,&nombre,&dni);
    Clave clave(&reg,2,"nombre","dni");
	BSharpTree* arbol = new BSharpTree(&clave);
	string nombreArchivo = "Daniel6";
	unsigned int tamanioBloque = 128;
	arbol->crear(nombreArchivo,tamanioBloque,&clave,comparador);
    delete arbol;
    BSharpTree* arbol2 = new BSharpTree(&clave);
    arbol2->abrir(nombreArchivo,comparador);
    numero=2;
    strncpy(unNombre,"abrego",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg2(2,&nombre,&dni);
    numero=3;
    strncpy(unNombre,"abrigo",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg3(2,&nombre,&dni);
    numero=4;
    strncpy(unNombre,"absida",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg4(2,&nombre,&dni);
    numero=5;
    strncpy(unNombre,"abside",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg5(2,&nombre,&dni);
    numero=6;
    strncpy(unNombre,"absit",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg6(2,&nombre,&dni);
    numero=7;
    strncpy(unNombre,"acana",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg7(2,&nombre,&dni);
    numero=8;
    strncpy(unNombre,"acaro",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg8(2,&nombre,&dni);
    numero=9;
    strncpy(unNombre,"acates",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg9(2,&nombre,&dni);
    numero=10;
    strncpy(unNombre,"acere",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg10(2,&nombre,&dni);
    numero=11;
    strncpy(unNombre,"acida",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg11(2,&nombre,&dni);
    numero=12;
    strncpy(unNombre,"acido",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg12(2,&nombre,&dni);
    numero=13;
    strncpy(unNombre,"acigos",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg13(2,&nombre,&dni);
    numero=14;
    strncpy(unNombre,"acimo",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg14(2,&nombre,&dni);
    numero=15;
    strncpy(unNombre,"acoro",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg15(2,&nombre,&dni);
    numero=16;
    strncpy(unNombre,"acrata",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg16(2,&nombre,&dni);
    numero=17;
    strncpy(unNombre,"acuea",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg17(2,&nombre,&dni);
    numero=18;
    strncpy(unNombre,"acueo",15);
    nombre.set(unNombre);
    dni.set(&numero);
    Registro reg18(2,&nombre,&dni);
    numero=19;
        strncpy(unNombre,"acula",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg19(2,&nombre,&dni);
        numero=20;
        strncpy(unNombre,"afaca",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg20(2,&nombre,&dni);
        numero=21;
        strncpy(unNombre,"afila",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg21(2,&nombre,&dni);
        numero=25;
        strncpy(unNombre,"afilo",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg25(2,&nombre,&dni);
        numero=26;
        strncpy(unNombre,"afona",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg26(2,&nombre,&dni);
        numero=27;
        strncpy(unNombre,"afono",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg27(2,&nombre,&dni);
        numero=28;
        strncpy(unNombre,"africa",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg28(2,&nombre,&dni);
        numero=29;
        strncpy(unNombre,"africo",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg29(2,&nombre,&dni);
        numero=30;
        strncpy(unNombre,"agape",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg30(2,&nombre,&dni);
        numero=31;
        strncpy(unNombre,"agata",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg31(2,&nombre,&dni);
        numero=32;
        strncpy(unNombre,"agil",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg32(2,&nombre,&dni);
        numero=33;
        strncpy(unNombre,"agilmente",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg33(2,&nombre,&dni);
        numero=34;
        strncpy(unNombre,"agora",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg34(2,&nombre,&dni);
        numero=35;
        strncpy(unNombre,"aguila",15);
        nombre.set(unNombre);
        dni.set(&numero);
        Registro reg35(2,&nombre,&dni);
        numero=36;
           strncpy(unNombre,"al",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg36(2,&nombre,&dni);
           numero=37;
           strncpy(unNombre,"alabe",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg37(2,&nombre,&dni);
           numero=38;
           strncpy(unNombre,"alaga",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg38(2,&nombre,&dni);
           numero=39;
           strncpy(unNombre,"alamo",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg39(2,&nombre,&dni);
           numero=40;
           strncpy(unNombre,"album",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg40(2,&nombre,&dni);
           numero=41;
           strncpy(unNombre,"alcali",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg41(2,&nombre,&dni);
           numero=42;
           strncpy(unNombre,"algebra",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg42(2,&nombre,&dni);
           numero=43;
           strncpy(unNombre,"algica",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg43(2,&nombre,&dni);
           numero=44;
           strncpy(unNombre,"algido",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg44(2,&nombre,&dni);
           numero=45;
           strncpy(unNombre,"alica",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg45(2,&nombre,&dni);
           numero=46;
           strncpy(unNombre,"aliger",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg46(2,&nombre,&dni);
           numero=47;
           strncpy(unNombre,"alimo",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg47(2,&nombre,&dni);
           numero=48;
           strncpy(unNombre,"aloe",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg48(2,&nombre,&dni);
           numero=49;
           strncpy(unNombre,"alsine",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg49(2,&nombre,&dni);
           numero=50;
           strncpy(unNombre,"alveo",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg50(2,&nombre,&dni);
           numero=51;
           strncpy(unNombre,"amago",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg51(2,&nombre,&dni);
           numero=52;
           strncpy(unNombre,"amala",15);
           nombre.set(unNombre);
           dni.set(&numero);
           Registro reg52(2,&nombre,&dni);
           numero=53;
               strncpy(unNombre,"amalo",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg53(2,&nombre,&dni);
               numero=54;
               strncpy(unNombre,"ambar",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg54(2,&nombre,&dni);
               numero=55;
               strncpy(unNombre,"ambito",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg55(2,&nombre,&dni);
               numero=56;
               strncpy(unNombre,"amel",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg56(2,&nombre,&dni);
               numero=57;
               strncpy(unNombre,"anade",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg57(2,&nombre,&dni);
               numero=58;
               strncpy(unNombre,"ancora",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg58(2,&nombre,&dni);
               numero=59;
               strncpy(unNombre,"andito",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg59(2,&nombre,&dni);
               numero=60;
               strncpy(unNombre,"anfora",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg60(2,&nombre,&dni);
               numero=61;
               strncpy(unNombre,"angaro",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg61(2,&nombre,&dni);
               numero=62;
               strncpy(unNombre,"angel",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg62(2,&nombre,&dni);
               numero=63;
               strncpy(unNombre,"angela",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg63(2,&nombre,&dni);
               numero=64;
               strncpy(unNombre,"angelus",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg64(2,&nombre,&dni);
               numero=65;
               strncpy(unNombre,"angulo",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg65(2,&nombre,&dni);
               numero=66;
               strncpy(unNombre,"anima",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg66(2,&nombre,&dni);
               numero=67;
               strncpy(unNombre,"animo",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg67(2,&nombre,&dni);
               numero=68;
               strncpy(unNombre,"anodo",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg68(2,&nombre,&dni);
               numero=69;
               strncpy(unNombre,"ansar",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg69(2,&nombre,&dni);
               numero=70;
               strncpy(unNombre,"antrax",15);
               nombre.set(unNombre);
               dni.set(&numero);
               Registro reg70(2,&nombre,&dni);
               numero=71;
                   strncpy(unNombre,"anula",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg71(2,&nombre,&dni);
                   numero=72;
                   strncpy(unNombre,"anulo",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg72(2,&nombre,&dni);
                   numero=73;
                   strncpy(unNombre,"apex",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg73(2,&nombre,&dni);
                   numero=74;
                   strncpy(unNombre,"apice",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg74(2,&nombre,&dni);
                   numero=76;
                   strncpy(unNombre,"apoca",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg76(2,&nombre,&dni);
                   numero=77;
                   strncpy(unNombre,"apoda",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg77(2,&nombre,&dni);
                   numero=78;
                   strncpy(unNombre,"apside",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg78(2,&nombre,&dni);
                   numero=79;
                   strncpy(unNombre,"aptera",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg79(2,&nombre,&dni);
                   numero=80;
                   strncpy(unNombre,"arabe",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg80(2,&nombre,&dni);
                   numero=81;
                   strncpy(unNombre,"arbitra",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg81(2,&nombre,&dni);
                   numero=83;
                   strncpy(unNombre,"arbitro",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg83(2,&nombre,&dni);
                   numero=84;
                   strncpy(unNombre,"arbol",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg84(2,&nombre,&dni);
                   numero=85;
                   strncpy(unNombre,"arbor",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg85(2,&nombre,&dni);
                   numero=86;
                   strncpy(unNombre,"arcade",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg86(2,&nombre,&dni);
                   numero=87;
                   strncpy(unNombre,"arctica",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg87(2,&nombre,&dni);
                   numero=88;
                   strncpy(unNombre,"ardea",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg88(2,&nombre,&dni);
                   numero=89;
                   strncpy(unNombre,"area",15);
                   nombre.set(unNombre);
                   dni.set(&numero);
                   Registro reg89(2,&nombre,&dni);
                   numero=90;
                       strncpy(unNombre,"argana",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg90(2,&nombre,&dni);
                       numero=91;
                       strncpy(unNombre,"arganas",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg91(2,&nombre,&dni);
                       numero=92;
                       strncpy(unNombre,"argano",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg92(2,&nombre,&dni);
                       numero=93;
                       strncpy(unNombre,"argoma",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg93(2,&nombre,&dni);
                       numero=94;
                       strncpy(unNombre,"arguenas",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg94(2,&nombre,&dni);
                       numero=95;
                       strncpy(unNombre,"arguenas",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg95(2,&nombre,&dni);
                       numero=96;
                       strncpy(unNombre,"arida",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg96(2,&nombre,&dni);
                       numero=98;
                       strncpy(unNombre,"arido",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg98(2,&nombre,&dni);
                       numero=99;
                       strncpy(unNombre,"arnica",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg99(2,&nombre,&dni);
                       numero=100;
                       strncpy(unNombre,"artabra",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg100(2,&nombre,&dni);
                       numero=101;
                       strncpy(unNombre,"artabro",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg101(2,&nombre,&dni);
                       numero=102;
                       strncpy(unNombre,"artica",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg102(2,&nombre,&dni);
                       numero=103;
                       strncpy(unNombre,"artico",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg103(2,&nombre,&dni);
                       numero=104;
                       strncpy(unNombre,"arula",15);
                       nombre.set(unNombre);
                       dni.set(&numero);
                       Registro reg104(2,&nombre,&dni);
                       numero=105;
                          strncpy(unNombre,"asaro",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg105(2,&nombre,&dni);
                          numero=106;
                          strncpy(unNombre,"ascar",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg106(2,&nombre,&dni);
                          numero=107;
                          strncpy(unNombre,"ascari",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg107(2,&nombre,&dni);
                          numero=109;
                          strncpy(unNombre,"asciro",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg109(2,&nombre,&dni);
                          numero=110;
                          strncpy(unNombre,"aspera",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg110(2,&nombre,&dni);
                          numero=111;
                          strncpy(unNombre,"aspero",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg111(2,&nombre,&dni);
                          numero=112;
                          strncpy(unNombre,"aspid",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg112(2,&nombre,&dni);
                          numero=113;
                          strncpy(unNombre,"aspide",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg113(2,&nombre,&dni);
                          numero=114;
                          strncpy(unNombre,"astaco",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg114(2,&nombre,&dni);
                          numero=115;
                          strncpy(unNombre,"atica",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg115(2,&nombre,&dni);
                          numero=116;
                          strncpy(unNombre,"atico",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg116(2,&nombre,&dni);
                          numero=117;
                          strncpy(unNombre,"atomo",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg117(2,&nombre,&dni);
                          numero=118;
                          strncpy(unNombre,"atona",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg118(2,&nombre,&dni);
                          numero=119;
                          strncpy(unNombre,"atono",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg119(2,&nombre,&dni);
                          numero=120;
                          strncpy(unNombre,"aulica",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg125(2,&nombre,&dni);
                          numero=126;
                          strncpy(unNombre,"aulico",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg126(2,&nombre,&dni);
                          numero=127;
                          strncpy(unNombre,"aurea",15);
                          nombre.set(unNombre);
                          dni.set(&numero);
                          Registro reg127(2,&nombre,&dni);
                          numero=128;
                              strncpy(unNombre,"aureo",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg128(2,&nombre,&dni);
                              numero=129;
                              strncpy(unNombre,"aurica",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg129(2,&nombre,&dni);
                              numero=130;
                              strncpy(unNombre,"aurico",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg130(2,&nombre,&dni);
                              numero=131;
                              strncpy(unNombre,"avida",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg131(2,&nombre,&dni);
                              numero=132;
                              strncpy(unNombre,"avidamente",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg132(2,&nombre,&dni);
                              numero=133;
                              strncpy(unNombre,"avido",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg133(2,&nombre,&dni);
                              numero=134;
                              strncpy(unNombre,"azimo",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg134(2,&nombre,&dni);
                              numero=135;
                              strncpy(unNombre,"azoe",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg135(2,&nombre,&dni);
                              numero=136;
                              strncpy(unNombre,"aaronica",15);
                              nombre.set(unNombre);
                              dni.set(&numero);
                              Registro reg136(2,&nombre,&dni);



    Clave clave2(&reg2,2,"nombre","dni");
    Clave clave3(&reg3,2,"nombre","dni");
    Clave clave4(&reg4,2,"nombre","dni");
    Clave clave5(&reg5,2,"nombre","dni");
    Clave clave6(&reg6,2,"nombre","dni");
    Clave clave7(&reg7,2,"nombre","dni");
    Clave clave8(&reg8,2,"nombre","dni");
    Clave clave37(&reg37,2,"nombre","dni");
    Clave clave9(&reg9,2,"nombre","dni");
    Clave clave10(&reg10,2,"nombre","dni");
    Clave clave40(&reg40,2,"nombre","dni");
    Clave clave36(&reg36,2,"nombre","dni");
    Clave clave65(&reg65,2,"nombre","dni");
    Clave clave45(&reg45,2,"nombre","dni");
    Clave clave11(&reg11,2,"nombre","dni");
    Clave clave48(&reg48,2,"nombre","dni");
    Clave clave50(&reg50,2,"nombre","dni");
    Clave clave38(&reg38,2,"nombre","dni");
    Clave clave12(&reg12,2,"nombre","dni");
    Clave clave13(&reg13,2,"nombre","dni");
    Clave clave61(&reg61,2,"nombre","dni");
    Clave clave68(&reg68,2,"nombre","dni");
    Clave clave39(&reg39,2,"nombre","dni");
    Clave clave14(&reg14,2,"nombre","dni");
    Clave clave15(&reg15,2,"nombre","dni");
    Clave clave47(&reg47,2,"nombre","dni");
    Clave clave16(&reg16,2,"nombre","dni");
    Clave clave41(&reg41,2,"nombre","dni");
    Clave clave42(&reg42,2,"nombre","dni");
    Clave clave17(&reg17,2,"nombre","dni");
    Clave clave19(&reg19,2,"nombre","dni");
    Clave clave46(&reg46,2,"nombre","dni");
    Clave clave18(&reg18,2,"nombre","dni");
        Clave clave20(&reg20,2,"nombre","dni");
        Clave clave52(&reg52,2,"nombre","dni");
        Clave clave51(&reg51,2,"nombre","dni");
        Clave clave49(&reg49,2,"nombre","dni");
        Clave clave44(&reg44,2,"nombre","dni");
        Clave clave21(&reg21,2,"nombre","dni");
        Clave clave43(&reg43,2,"nombre","dni");
        Clave clave25(&reg25,2,"nombre","dni");
        Clave clave26(&reg26,2,"nombre","dni");
        Clave clave27(&reg27,2,"nombre","dni");
        Clave clave28(&reg28,2,"nombre","dni");
        Clave clave53(&reg52,2,"nombre","dni");
        Clave clave54(&reg54,2,"nombre","dni");
        Clave clave55(&reg55,2,"nombre","dni");
        Clave clave29(&reg29,2,"nombre","dni");
        Clave clave30(&reg30,2,"nombre","dni");
        Clave clave31(&reg31,2,"nombre","dni");
        Clave clave33(&reg33,2,"nombre","dni");
        Clave clave56(&reg56,2,"nombre","dni");
        Clave clave34(&reg34,2,"nombre","dni");
        Clave clave57(&reg57,2,"nombre","dni");
        Clave clave35(&reg35,2,"nombre","dni");
        Clave clave58(&reg58,2,"nombre","dni");
        Clave clave59(&reg59,2,"nombre","dni");
        Clave clave32(&reg32,2,"nombre","dni");
                Clave clave63(&reg63,2,"nombre","dni");
                Clave clave64(&reg64,2,"nombre","dni");
                Clave clave66(&reg66,2,"nombre","dni");
                Clave clave67(&reg35,2,"nombre","dni");
                Clave clave60(&reg60,2,"nombre","dni");
                Clave clave62(&reg62,2,"nombre","dni");
                Clave clave69(&reg69,2,"nombre","dni");
                    Clave clave71(&reg71,2,"nombre","dni");
                    Clave clave72(&reg72,2,"nombre","dni");
                    Clave clave73(&reg73,2,"nombre","dni");
                    Clave clave74(&reg74,2,"nombre","dni");
                    Clave clave76(&reg76,2,"nombre","dni");
                    Clave clave77(&reg77,2,"nombre","dni");
                    Clave clave78(&reg78,2,"nombre","dni");
                    Clave clave79(&reg79,2,"nombre","dni");
                    Clave clave80(&reg80,2,"nombre","dni");
                    Clave clave83(&reg83,2,"nombre","dni");
                    Clave clave84(&reg84,2,"nombre","dni");
                    Clave clave85(&reg85,2,"nombre","dni");
                    Clave clave86(&reg86,2,"nombre","dni");
                    Clave clave87(&reg87,2,"nombre","dni");
                    Clave clave88(&reg88,2,"nombre","dni");
                    Clave clave89(&reg89,2,"nombre","dni");
                    Clave clave90(&reg90,2,"nombre","dni");
                    Clave clave91(&reg91,2,"nombre","dni");
                    Clave clave92(&reg92,2,"nombre","dni");
                    Clave clave93(&reg93,2,"nombre","dni");
                    Clave clave94(&reg94,2,"nombre","dni");
                    Clave clave95(&reg95,2,"nombre","dni");
                    Clave clave96(&reg96,2,"nombre","dni");
                    Clave clave98(&reg98,2,"nombre","dni");
                    Clave clave99(&reg99,2,"nombre","dni");
                    Clave clave100(&reg100,2,"nombre","dni");
                    Clave clave101(&reg101,2,"nombre","dni");
                    Clave clave102(&reg102,2,"nombre","dni");
                    Clave clave103(&reg103,2,"nombre","dni");
                        Clave clave104(&reg104,2,"nombre","dni");
                        Clave clave105(&reg105,2,"nombre","dni");
                        Clave clave106(&reg106,2,"nombre","dni");
                        Clave clave107(&reg107,2,"nombre","dni");
                        Clave clave109(&reg109,2,"nombre","dni");
                        Clave clave110(&reg110,2,"nombre","dni");
                        Clave clave111(&reg111,2,"nombre","dni");
                        Clave clave112(&reg112,2,"nombre","dni");
                        Clave clave113(&reg113,2,"nombre","dni");
                        Clave clave114(&reg114,2,"nombre","dni");
                        Clave clave115(&reg115,2,"nombre","dni");
                        Clave clave116(&reg116,2,"nombre","dni");
                        Clave clave117(&reg117,2,"nombre","dni");
                        Clave clave118(&reg118,2,"nombre","dni");
                        Clave clave119(&reg119,2,"nombre","dni");
                        Clave clave125(&reg125,2,"nombre","dni");
                        Clave clave126(&reg126,2,"nombre","dni");
                        Clave clave127(&reg127,2,"nombre","dni");
                        Clave clave128(&reg128,2,"nombre","dni");
                        Clave clave129(&reg129,2,"nombre","dni");
                        Clave clave130(&reg130,2,"nombre","dni");
                        Clave clave131(&reg131,2,"nombre","dni");
                        Clave clave132(&reg132,2,"nombre","dni");
                        Clave clave133(&reg133,2,"nombre","dni");
                        Clave clave134(&reg134,2,"nombre","dni");
                        Clave clave135(&reg135,2,"nombre","dni");
                        Clave clave136(&reg136,2,"nombre","dni");


    Referencia ref2 = 2;
    Referencia ref3 = 3;
    Referencia ref4 = 4;
    Referencia ref5 = 5;
    Referencia ref6 = 6;
    Referencia ref7 = 7;
    Referencia ref8 = 8;
    Referencia ref9 = 9;
    Referencia ref10 = 10;
    Referencia ref11 = 11;
    Referencia ref12 = 12;
    Referencia ref13 = 13;
    Referencia ref14 = 14;
    Referencia ref15 = 15;
    Referencia ref16 = 16;
    Referencia ref17 = 17;
    Referencia ref18 = 18;
    Referencia ref19 = 19;
       Referencia ref20 = 20;
       Referencia ref21 = 21;
       Referencia ref25= 25;
       Referencia ref26= 26;
       Referencia ref27= 27;
       Referencia ref28= 28;
       Referencia ref29= 29;
       Referencia ref30= 30;
       Referencia ref31= 31;
       Referencia ref32= 32;
       Referencia ref33= 33;
       Referencia ref34= 34;
       Referencia ref35= 35;
       Referencia ref36 = 36;
           Referencia ref37 = 37;
           Referencia ref38 = 38;
           Referencia ref39 = 39;
           Referencia ref40 = 40;
           Referencia ref41 = 41;
           Referencia ref42 = 42;
           Referencia ref43 = 43;
           Referencia ref44 = 44;
           Referencia ref45 = 45;
           Referencia ref46 = 46;
           Referencia ref47 = 47;
           Referencia ref48 = 48;
           Referencia ref49 = 49;
           Referencia ref50 = 50;
           Referencia ref51 = 51;
           Referencia ref52 = 52;
           Referencia ref53 = 53;
              Referencia ref54 = 54;
              Referencia ref55 = 55;
              Referencia ref56= 56;
              Referencia ref57= 57;
              Referencia ref58= 58;
              Referencia ref59= 59;
              Referencia ref60= 60;
              Referencia ref61= 61;
              Referencia ref62= 62;
              Referencia ref63= 63;
              Referencia ref64= 64;
              Referencia ref65= 65;
              Referencia ref66 = 66;
              Referencia ref67= 67;
              Referencia ref68= 68;
              Referencia ref69= 69;
              Referencia ref100 = 100;
                  Referencia ref71 = 71;
                  Referencia ref72 = 3;
                  Referencia ref73 = 4;
                  Referencia ref74 = 5;
                  Referencia ref75 = 6;
                  Referencia ref76 = 7;
                  Referencia ref77 = 8;
                  Referencia ref78 = 9;
                  Referencia ref79 = 10;
                  Referencia ref80 = 11;
                  Referencia ref81 = 12;
                  Referencia ref82 = 13;
                  Referencia ref83 = 14;
                  Referencia ref84 = 15;
                  Referencia ref85 = 16;
                  Referencia ref86 = 17;
                  Referencia ref87 = 18;
                  Referencia ref88 = 19;
                     Referencia ref89 = 20;
                     Referencia ref90 = 21;
                     Referencia ref91= 25;
                     Referencia ref92= 26;
                     Referencia ref93= 27;
                     Referencia ref94= 28;
                     Referencia ref95= 29;
                     Referencia ref96= 30;
                     Referencia ref97= 31;
                     Referencia ref98= 32;
                     Referencia ref99= 33;
                     Referencia ref101= 34;
                     Referencia ref102= 35;
                     Referencia ref103 = 36;
                         Referencia ref104 = 37;
                         Referencia ref105 = 38;
                         Referencia ref106 = 39;
                         Referencia ref107 = 40;
                         Referencia ref108 = 41;
                         Referencia ref109 = 42;
     ;
                         Referencia ref111 = 44;
                         Referencia ref112 = 45;
                         Referencia ref113 = 46;
                         Referencia ref114 = 47;
                         Referencia ref115 = 48;
                         Referencia ref116 = 49;
                         Referencia ref117 = 50;
                         Referencia ref118 = 51;
                         Referencia ref119 = 52;
                         Referencia ref120 = 53;
                            Referencia ref121 = 54;
                            Referencia ref122 = 55;
                            Referencia ref123= 56;
                            Referencia ref124= 57;
                            Referencia ref125= 58;
                            Referencia ref126= 59;
                            Referencia ref127= 60;
                            Referencia ref128= 61;
                            Referencia ref129= 62;
                            Referencia ref130= 63;
                            Referencia ref131= 64;

              std::list<ElementoNodo*>::iterator it;
    arbol2->insertar(ref6,&clave6);
    arbol2->insertar(ref3,&clave3);
    arbol2->insertar(ref36,&clave36);
    arbol2->insertar(ref5,&clave5);
    arbol2->insertar(ref4,&clave4);
    arbol2->insertar(ref40,&clave40);
    arbol2->insertar(ref2,&clave2);
    arbol2->insertar(ref7,&clave7);
    arbol2->insertar(ref9,&clave9);
    arbol2->insertar(ref38,&clave38);
    arbol2->insertar(ref50,&clave50);
    arbol2->insertar(ref37,&clave37);
    arbol2->insertar(ref15,&clave15);
    arbol2->insertar(ref10,&clave10);
    arbol2->insertar(ref56,&clave56);
    arbol2->insertar(ref57,&clave57);
    arbol2->insertar(ref15,&clave15);
    arbol2->insertar(ref10,&clave10);
    arbol2->insertar(ref56,&clave56);
    arbol2->insertar(ref57,&clave57);
    arbol2->insertar(ref58,&clave58);
    arbol2->insertar(ref59,&clave59);
    arbol2->insertar(ref8,&clave8);
    arbol2->insertar(ref12,&clave12);
    arbol2->insertar(ref13,&clave13);
    arbol2->insertar(ref14,&clave14);
    arbol2->insertar(ref47,&clave47);
    arbol2->insertar(ref42,&clave42);
    arbol2->insertar(ref45,&clave45);
    arbol2->insertar(ref46,&clave46);
    arbol2->insertar(ref44,&clave44);
    arbol2->insertar(ref43,&clave43);
    arbol2->insertar(ref63,&clave63);
    arbol2->insertar(ref64,&clave64);
    arbol2->insertar(ref65,&clave65);
    arbol2->insertar(ref66,&clave66);
    arbol2->insertar(ref67,&clave67);
    arbol2->insertar(ref17,&clave17);
    arbol2->insertar(ref19,&clave19);
    arbol2->insertar(ref11,&clave11);
    arbol2->insertar(ref60,&clave60);
    arbol2->insertar(ref61,&clave61);
    arbol2->insertar(ref62,&clave62);
                 arbol2->insertar(ref20,&clave20);
                 arbol2->insertar(ref41,&clave41);
                 arbol2->insertar(ref21,&clave21);
                 arbol2->insertar(ref54,&clave54);
                 arbol2->insertar(ref16,&clave16);
                 arbol2->insertar(ref18,&clave18);
                arbol2->insertar(ref51,&clave51);
                arbol2->insertar(ref52,&clave52);
                arbol2->insertar(ref25,&clave25);
                arbol2->insertar(ref26,&clave26);
                arbol2->insertar(ref27,&clave27);
                arbol2->insertar(ref53,&clave53);
                arbol2->insertar(ref28,&clave28);
                arbol2->insertar(ref55,&clave55);
                arbol2->insertar(ref68,&clave68);
                arbol2->insertar(ref54,&clave54);
                arbol2->insertar(ref69,&clave69);
                arbol2->insertar(ref29,&clave29);
                    arbol2->insertar(ref30,&clave30);
                    arbol2->insertar(ref31,&clave31);
                    arbol2->insertar(ref48,&clave48);
                    arbol2->insertar(ref49,&clave49);
                    arbol2->insertar(ref32,&clave32);
                    arbol2->insertar(ref33,&clave33);
                    arbol2->insertar(ref34,&clave34);
                    arbol2->insertar(ref39,&clave39);
                    arbol2->insertar(ref35,&clave35);

                    arbol2->insertar(ref71,&clave71);
                    arbol2->insertar(ref72,&clave37);
                    arbol2->insertar(ref73,&clave15);
                    arbol2->insertar(ref74,&clave10);
                    arbol2->insertar(ref75,&clave56);
                    arbol2->insertar(ref76,&clave57);
                    arbol2->insertar(ref77,&clave15);
                    arbol2->insertar(ref78,&clave10);
                    arbol2->insertar(ref79,&clave56);
                    arbol2->insertar(ref80,&clave57);
                    arbol2->insertar(ref81,&clave58);
                    arbol2->insertar(ref82,&clave59);
                    arbol2->insertar(ref83,&clave8);
                    arbol2->insertar(ref84,&clave12);
                    arbol2->insertar(ref85,&clave13);
                    arbol2->insertar(ref86,&clave14);
                    arbol2->insertar(ref87,&clave47);
                    arbol2->insertar(ref88,&clave42);
                    arbol2->insertar(ref89,&clave45);
                    arbol2->insertar(ref90,&clave46);
                    arbol2->insertar(ref91,&clave44);
                    arbol2->insertar(ref92,&clave43);
                    arbol2->insertar(ref93,&clave63);
                    arbol2->insertar(ref94,&clave64);
                    arbol2->insertar(ref95,&clave65);
                    arbol2->insertar(ref96,&clave66);
                    arbol2->insertar(ref97,&clave67);
                    arbol2->insertar(ref98,&clave17);
                    arbol2->insertar(ref99,&clave19);
                    arbol2->insertar(ref100,&clave11);
                    arbol2->insertar(ref101,&clave60);
                    arbol2->insertar(ref102,&clave61);
                    arbol2->insertar(ref103,&clave62);
                                 arbol2->insertar(ref104,&clave20);
                                 arbol2->insertar(ref105,&clave41);
                                 arbol2->insertar(ref106,&clave21);
                                 arbol2->insertar(ref107,&clave54);
                                 arbol2->insertar(ref108,&clave16);
                                 arbol2->insertar(ref109,&clave18);
                                arbol2->insertar(ref111,&clave51);
                                arbol2->insertar(ref112,&clave52);
                                arbol2->insertar(ref113,&clave25);
                                arbol2->insertar(ref114,&clave26);
                                arbol2->insertar(ref115,&clave27);
                                arbol2->insertar(ref116,&clave53);
                                arbol2->insertar(ref117,&clave28);
                                arbol2->insertar(ref118,&clave55);
                                /*------------------------*/
                                /*Busco un elemento*/
                                encontrado = arbol2->Buscar(&clave27,&refAux);
                                if(encontrado && refAux == 27){
                                	cout << "todo Ok"<< "Referencia Buscada"<<refAux<<endl;
                                }else{
                                	cout<<"Mal"<<endl;
                                }
                                /*modifico dicho valor*/
                                refAux = 1899;
                                arbol2->modificar(&clave27,refAux);
                                /*------Vuelvo a buscar-----*/
                                encontrado = arbol2->Buscar(&clave27,&refAux);
                                if(encontrado && refAux == 1899){
                                      cout << "todo Ok"<< "Referencia Buscada"<<refAux<<endl;
                                 }else{
                                      cout<<"Mal"<<endl;
                                }
                                refAux=arbol2->Siguiente(true);
                                cout<<"El sigueinte es"<<refAux<<endl;
                                arbol2->insertar(ref119,&clave68);
                                arbol2->insertar(ref120,&clave54);
                                arbol2->insertar(ref121,&clave69);
                                arbol2->insertar(ref122,&clave29);
                                    arbol2->insertar(ref123,&clave30);
                                    arbol2->insertar(ref124,&clave31);
                                    arbol2->insertar(ref125,&clave48);
                                    arbol2->insertar(ref126,&clave49);
                                    arbol2->insertar(ref127,&clave32);
                                    arbol2->insertar(ref128,&clave33);
                                    arbol2->insertar(ref129,&clave34);
                                    arbol2->insertar(ref130,&clave39);
                                    arbol2->insertar(ref131,&clave35);
                    arbol2->imprimir();

                    arbol2->eliminar(&clave4);
                    arbol2->eliminar(&clave5);
                    arbol2->eliminar(&clave6);
                    arbol2->eliminar(&clave7);
                    arbol2->eliminar(&clave60);
                    arbol2->eliminar(&clave61);
                    arbol2->eliminar(&clave69);
                    encontrado = arbol2->Buscar(&clave61,&refAux);
                    if(!encontrado)cout << "OK, el elemento fue elimando"<<endl;
                    arbol2->eliminar(&clave64);
                    arbol2->eliminar(&clave68);
                    arbol2->eliminar(&clave50);
                    arbol2->eliminar(&clave51);
                    arbol2->eliminar(&clave52);
                    arbol2->eliminar(&clave46);
                    arbol2->eliminar(&clave47);
                    arbol2->eliminar(&clave48);
                    arbol2->eliminar(&clave45);
                    arbol2->eliminar(&clave49);
                    arbol2->eliminar(&clave41);
                    arbol2->eliminar(&clave40);
                    arbol2->eliminar(&clave42);
                    arbol2->eliminar(&clave43);
                    arbol2->eliminar(&clave44);
                    arbol2->imprimir();

	                return 0;
};


