#created on: 18/06/2010
package soluciones

#list any import classes here.
import asistenteMecanico.client.model.*;
import asistenteMecanico.client.utils.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;

#declare any global variables here

rule "Inicia asistente mecanico. FrontDrools esta vacio."
    when
    	$ui: FrontDrools( enumDefecto == null )
    then
	    ArrayList<EnumAsistente> defectos = new ArrayList();
			defectos.add(EnumDefectos.D1);
			defectos.add(EnumDefectos.D2);
			defectos.add(EnumDefectos.D3);
			defectos.add(EnumDefectos.D4);
			defectos.add(EnumDefectos.D6);
			defectos.add(EnumDefectos.D7);
			defectos.add(EnumDefectos.D8);
			defectos.add(EnumDefectos.D9);
			defectos.add(EnumDefectos.D10);
			defectos.add(EnumDefectos.D11);
			defectos.add(EnumDefectos.D12);
		$ui.setList(defectos);
end

rule "FrontDrools cambio"
	when 
		ui: FrontDrools( change == true )
	then
		insert(new Defecto( ui.getEnumDefecto() ) );
end

rule "Trabajo con soluciones."
	when
		ui: FrontDrools( )
		defectos: ArrayList() from collect ( Defecto( ) )
    	ArrayList( size == 1 ) from collect ( Solucion() )
    	solucion : Solucion(  )
	then 
		ArrayList<EnumAsistente> listTemp = new ArrayList<EnumAsistente>();
		Iterator<Defecto> it = defectos.iterator();
		while ( it.hasNext() ){
			listTemp.add(it.next().getDescripcion());
		}
		ui.setEnumDefecto(null);
		ui.setSolucion(true);
		ui.setEnumSolucion(solucion.getDescripcion());
		ui.setList(listTemp);
end
