package asistenteMecanico.rules

import asistenteMecanico.client.model.*;
import asistenteMecanico.client.utils.*;
import java.util.ArrayList;

rule "Se opto por una regla comun a todos los problemas."
    when
    	defecto: Defecto( 
    			descripcion == EnumDefectos.D1	||
    			descripcion == EnumDefectos.D6	||
    			descripcion == EnumDefectos.D11	||
    			descripcion == EnumDefectos.D12	)
    	ui: FrontDrools( )
    	ArrayList( size == 1 ) from collect ( Defecto() )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
    	ArrayList<EnumAsistente> defectos = new ArrayList();
    	defectos.add(EnumDefectos.D4); 
		defectos.add(EnumDefectos.D7);
		ui.setList( defectos );
end

rule "solo tengo una regla comun a todos los problemas."
    when
    	Defecto(descripcion == EnumDefectos.D1	||
    			descripcion == EnumDefectos.D6	||
    			descripcion == EnumDefectos.D11	||
    			descripcion == EnumDefectos.D12	)
    	ui: FrontDrools( sinSeleccion == true )
    	ArrayList( size == 1 ) from collect ( Defecto() )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert(new Solucion(EnumSoluciones.S5));
end

rule "Con los defectos: D2"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D2 )
    	ui: FrontDrools( )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D2 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then
	    ArrayList<EnumAsistente> defectos = new ArrayList();
		defectos.add(EnumDefectos.D3);
		defectos.add(EnumDefectos.D9);
		ui.setList(defectos);
end

rule "Con los defectos: D2 y D3 0 D9"
    when
    	Defecto( descripcion == EnumDefectos.D2 )
		Defecto( descripcion == EnumDefectos.D3 || 
				 descripcion == EnumDefectos.D9 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D2 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then
		insert(new Solucion(EnumSoluciones.S6));
end 

rule "Con los defectos: D2 y nada mas"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D2 )
    	ui: FrontDrools( sinSeleccion == true )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D2 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then
		insert(new Solucion(EnumSoluciones.S2));
end

rule "Con los defectos: D3"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D3 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D3 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then
		insert( new Solucion(EnumSoluciones.S6) );
end

rule "Con los defectos: D4"
    when
    	Defecto(descripcion == EnumDefectos.D4 )
    	ui: FrontDrools()
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D4 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
    	ArrayList<EnumAsistente> defectos = new ArrayList();
		defectos.add(EnumDefectos.D2);
		defectos.add(EnumDefectos.D3);
		defectos.add(EnumDefectos.D9);
    	defectos.add(EnumDefectos.D8);
    	defectos.add(EnumDefectos.D10);
		ui.setList(defectos);
end

rule "Con los defectos: D4 y nada mas"
    when
    	Defecto(descripcion == EnumDefectos.D4 )
    	ui: FrontDrools( sinSeleccion == true )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D4 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert(new Solucion(EnumSoluciones.S2));
end
rule "Con los defectos: D4 y d8 o d10"
    when
		Defecto(descripcion == EnumDefectos.D4)
		Defecto( descripcion == EnumDefectos.D8 || 
				 descripcion == EnumDefectos.D10 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D4 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert(new Solucion(EnumSoluciones.S1));
end

rule "Con los defectos: D4 y d2 o d3 o D9"
    when
		Defecto(descripcion == EnumDefectos.D4)
		Defecto( descripcion == EnumDefectos.D2 || 
				 descripcion == EnumDefectos.D3 || 
				 descripcion == EnumDefectos.D9  )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D4 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert(new Solucion(EnumSoluciones.S6));
end

rule "Con los defectos: D7"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D7 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D7 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert( new Solucion(EnumSoluciones.S4) );
end


rule "Con los defectos: D8"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D8 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D8 ) )
    	ArrayList( size == 0 ) from collect ( Solucion(  ) )
    	ui: FrontDrools(  )
    then 
    	ArrayList<EnumAsistente> defectos = new ArrayList();
    	defectos.add(EnumDefectos.D2); 
    	ui.setList(defectos);
end

rule "Con los defectos: D8 y D2"
    when
    	Defecto( descripcion == EnumDefectos.D8 ,
    			 descripcion == EnumDefectos.D2 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D8 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert(new Solucion(EnumSoluciones.S3));
end

rule "Con los defectos: D8 y nada mas"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D8 )
    	FrontDrools( sinSeleccion == true )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D8 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
    	insert(new Solucion(EnumSoluciones.S4));
end

rule "Con los defectos: D9"
    when
    	Defecto( descripcion == EnumDefectos.D9 )
    	ui: FrontDrools(  )
		ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D9 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
    	ArrayList<EnumAsistente> defectos = new ArrayList();
    	defectos.add(EnumDefectos.D3); 
    	ui.setList(defectos);
end

rule "Con los defectos: D9 y D3"
	when
    	Defecto( descripcion == EnumDefectos.D9 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D9 ) )
    	Defecto( descripcion == EnumDefectos.D3 )
		ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D3 ) )
    then
		insert(new Solucion(EnumSoluciones.S6));
end

rule "Con los defectos: D9 y no D3"
	when
    	Defecto( descripcion == EnumDefectos.D9 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D9 ) )
    	FrontDrools( sinSeleccion == true )
	then
		insert(new Solucion(EnumSoluciones.S1));
end

rule "Con los defectos: D10"
    when
    	defecto: Defecto( descripcion == EnumDefectos.D10 )
    	ArrayList( size == 1 ) from collect ( Defecto( descripcion == EnumDefectos.D10 ) )
    	ArrayList( size == 0 ) from collect ( Solucion() )
    then 
		insert(new Solucion(EnumSoluciones.S1));
end