/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Aumento.java
 *
 * Created on 24/06/2011, 07:17:08
 */
package fi.uba.drools.poker.view;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;

import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author Federico
 */
public class Aumento extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    
	String textoRecomendacion;
	private Container panelPrincipal;

    /** Creates new form Aumento */
    public Aumento() {
        initComponents();
        this.setResizable(false);
    }
    private void cargarEstilo(JComponent component){
    	component.setForeground(Color.decode("#000000"));
    	component.setBackground(Color.decode("#ffffff"));
    	component.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 14));
        
    }
    private void cargarEstiloLabel(JLabel component){
    	component.setForeground(Color.decode("#000000"));
    	component.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 14));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aumentoJugador = new javax.swing.JSpinner();
        cargarEstilo(aumentoJugador);
        aumentoOponente = new javax.swing.JSpinner();
        cargarEstilo(aumentoOponente);
        botonContinuar = new javax.swing.JButton();
        cargarEstilo(botonContinuar);
        label1 = new JLabel();
        label2 = new JLabel();
        cargarEstiloLabel(label1);
        cargarEstiloLabel(label2);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        botonContinuar.setText("Continuar");
//        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                botonContinuarActionPerformed(evt);
//            }
//        });

        label1.setText("Cuanto apostó el Jugador?");

        label2.setText("Cuanto aumentó el Oponente?");
        this.panelPrincipal= new PanelPrincipal();
        this.getContentPane().add(this.panelPrincipal);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.panelPrincipal);
        this.panelPrincipal.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aumentoJugador)
                            .addComponent(aumentoOponente, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(botonContinuar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aumentoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(botonContinuar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
//        
//        /*
//         * 
//         * 
//         * para obtener cuanto aumentaron:
//         * aumentoJugador.getValue()
//         * aumentoOponente.getValue()
//         * (devuelve int)
//         * 
//         * 
//         * 
//         * si el oponente sigue aumentando va a pasar siempre poc aca
//         * 
//         * 
//         * 
//         * 
//         * 
//         * el text a recomendar esta justo abajo de este comentario
//         * 
//         * 
//         * 
//         * 
//         * 
//         * 
//         */
//        
//        textoRecomendacion = "Insertar aqui el texto de cuando el "+
//                "sistema experto le recomienda al usuario lo que tiene que"+
//                "hacer si el oponente sigue apostando";
//        this.setVisible(false);
//        new Recomendacion(textoRecomendacion).setVisible(true);
//    }//GEN-LAST:event_botonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Aumento().setVisible(true);
            }
        });
    }
    
    public void addContinueListener(java.awt.event.ActionListener listener){
    	botonContinuar.addActionListener(listener);
    }
    
    public Integer getPlayerBet(){
		return (Integer)aumentoJugador.getValue();
	}
	public Integer getOpponentBet(){
		return (Integer)aumentoOponente.getValue();
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aumentoJugador;
    private javax.swing.JSpinner aumentoOponente;
    private javax.swing.JButton botonContinuar;
    private JLabel label1;
    private JLabel label2;
    // End of variables declaration//GEN-END:variables
}
