/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Priciapl.java
 *
 * Created on 24/06/2011, 01:06:04
 */
package fi.uba.drools.poker.view;
import javax.swing.*;

import java.awt.*;
import java.awt.*;
import java.awt.event.*;
import java.util.HashMap;

import javax.swing.*;

import fi.uba.drools.poker.models.Card;
import fi.uba.drools.poker.utils.ResourceManager;

/**
 *
 * @author Federico
 */
public class Principal extends javax.swing.JFrame {

    Card carta1;
    Card carta2;
    String textoRecomendacion;
    HashMap< String, String> mapSuit= new  HashMap<String, String>();
    private JPanel panelPrincipal =null;
    /** Creates new form Priciapl */
    public Principal() {
        carta1 = new Card(Card.ACE,Card.HEARTS);
        carta2 = new Card(Card.ACE,Card.HEARTS);
        initComponents();
        updateLabel (carta1,labelImagen1);
        updateLabel (carta2,labelImagen2);
        this.setResizable(false);
    }
    private void cargarEstilo(JComponent component){
    	component.setBackground(Color.decode("#ffffff"));
    	component.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 14));
        
    }
    private void cargarEstiloLabel(Label component){
    	component.setBackground(Color.decode("#ffffff"));
    	component.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 14));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero1 = new javax.swing.JComboBox();
        palo1 = new javax.swing.JComboBox();
        numero2 = new javax.swing.JComboBox();
        palo2 = new javax.swing.JComboBox();
        cargarEstilo(numero1);
        cargarEstilo(numero2);
        cargarEstilo(palo1);
        cargarEstilo(palo2);
        luzGrande = new javax.swing.JCheckBox();
        cargarEstilo(luzGrande);
        labelFichas1 = new java.awt.Label();
        cargarEstiloLabel(labelFichas1);
        labelCartas = new java.awt.Label();
        labelCartas.setBackground(Color.decode("#ffffff"));
        labelCartas.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 20));
        labelCartas.setForeground(Color.decode("#565656"));
        labelApostadas1 = new java.awt.Label();
        cargarEstiloLabel(labelApostadas1);
        labelJugador1 = new java.awt.Label();
        cargarEstiloLabel(labelJugador1);
        jSeparator1 = new javax.swing.JSeparator();
        labelFichas2 = new java.awt.Label();
        cargarEstiloLabel(labelFichas2);
        labelApostadas2 = new java.awt.Label();
        cargarEstiloLabel(labelApostadas2);
        jSeparator2 = new javax.swing.JSeparator();
        labelJugador2 = new java.awt.Label();
        cargarEstiloLabel(labelJugador2);
        personalidadOponente = new javax.swing.JComboBox();
        cargarEstilo(personalidadOponente);
        buttonRecomendar = new javax.swing.JButton();
        buttonRecomendar.setBackground(Color.decode("#ffffff"));
        buttonRecomendar.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 24));
        buttonRecomendar.setHorizontalTextPosition(AbstractButton.CENTER);
        buttonRecomendar.setVerticalTextPosition(AbstractButton.BOTTOM);
      
        labelImagen1 = new javax.swing.JLabel();
        labelImagen2 = new javax.swing.JLabel();
        fichasJugador = new javax.swing.JSpinner();
        cargarEstilo(fichasJugador);
        fichasApostadasJugador = new javax.swing.JSpinner();
        cargarEstilo(fichasApostadasJugador);
        fichasApostadasOponente = new javax.swing.JSpinner();
        cargarEstilo(fichasApostadasOponente);
        fichasOponente = new javax.swing.JSpinner();
        cargarEstilo(fichasOponente);
        jMenuBar1 = new javax.swing.JMenuBar();
        cargarEstilo(jMenuBar1);
        menuArchivo = new javax.swing.JMenu();
        cargarEstilo(menuArchivo);
        menuItemReiniciar = new javax.swing.JMenuItem();
        cargarEstilo(menuItemReiniciar);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 153, 0));
//        setBounds(new java.awt.Rectangle(0, 150, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        numero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "A", "2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K" }));
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });
        mapSuit.put("Diamantes","d");
        mapSuit.put("Tréboles","c");
        mapSuit.put("Corazones","h");
        mapSuit.put( "Picas","s");
        palo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Corazones", "Diamantes", "Picas", "Tréboles" }));
        palo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                palo1ItemStateChanged(evt);
            }
        });
        palo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palo1ActionPerformed(evt);
            }
        });

        numero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K"  }));
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        palo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Corazones", "Diamantes", "Picas", "Tréboles" }));
        palo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palo2ActionPerformed(evt);
            }
        });

        luzGrande.setText("Luz Grande");

        labelFichas1.setText("Fichas");

        labelCartas.setText("Sistema Experto de Poker Texas Holdem");

        labelApostadas1.setText("Apostado");

        labelJugador1.setText("Jugador");

        labelFichas2.setText("Fichas");

        labelApostadas2.setText("Apostado");

        labelJugador2.setText("Oponente");

        personalidadOponente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agresivo", "Ajustado" }));

        buttonRecomendar.setText("Recomendar Jugada");
        buttonRecomendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRecomendarActionPerformed(evt);
            }
        });

        labelImagen1.setText("jLabel1");

        labelImagen2.setText("jLabel2");

        menuArchivo.setText("Archivo");

        menuItemReiniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemReiniciar.setText("Reiniciar");
        menuItemReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReiniciarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemReiniciar);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);
        this.panelPrincipal= new PanelPrincipal();
        this.getContentPane().add(this.panelPrincipal);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.panelPrincipal);
        this.panelPrincipal.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fichasOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(fichasApostadasOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(personalidadOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(fichasApostadasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(fichasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFichas1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(luzGrande)
                                    .addComponent(labelApostadas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                            .addComponent(buttonRecomendar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelFichas2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(labelApostadas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE,80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(labelImagen2, javax.swing.GroupLayout.PREFERRED_SIZE,80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJugador1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luzGrande, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFichas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApostadas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fichasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fichasApostadasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalidadOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelApostadas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFichas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fichasOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fichasApostadasOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(buttonRecomendar)
                .addGap(38, 38, 38)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palo1ActionPerformed
        carta1.setSuit(carta1.getSuit(mapSuit.get((String)palo1.getSelectedItem())));
        updateLabel (carta1,labelImagen1);
        return;
}//GEN-LAST:event_palo1ActionPerformed

    private void palo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palo2ActionPerformed
    	  carta2.setSuit(carta2.getSuit(mapSuit.get((String)palo2.getSelectedItem())));
        updateLabel (carta2,labelImagen2);
        return;
}//GEN-LAST:event_palo2ActionPerformed

    private void menuItemReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReiniciarActionPerformed
     
      this.reset();
      return;
    }//GEN-LAST:event_menuItemReiniciarActionPerformed

    public void reset (){
      this.setVisible(false);
      new Principal().setVisible(true); 
      return;
    }
    private void palo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_palo1ItemStateChanged
        // DELETE
    }//GEN-LAST:event_palo1ItemStateChanged

    private void buttonRecomendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecomendarActionPerformed
        
        
        /*
         * 
         * aqui tiene que ir el codigo del recomendador:
         * Para obtener las carta1 y carta2:
         * carta1.getPalo()   {devulve el string con el palo)
         * carta2.getNumero() {devuelve un numero del 1 al 13)
         * 
         * para obtener si es luz grande:
         * luzGrande.getState() [devuelve un booleando, verdadero si es luz grande}
         * 
         * para obtener las fichas: 
         * fichasApostadasJugador.getValue()
         * fichasApostadasOponente.getValue()
         * fichasJugador.getValue()
         * fichasOponente.getValue()
         * (devuelve un int)
         * 
         * Para obtener la personalidad:
         * personalidadOponente.getSelectedItem()
         * (devuelve un String)
         * 
         * 
         * 
         * el text a recomendar esta justo abajo de este comentario
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         * 
         */
        textoRecomendacion = "Insertar aqui el texto de lo que sea que recomiende el "+
                "sistema experto.";
        
        new Recomendacion(textoRecomendacion,this).setVisible(true);
        
        
        
    }//GEN-LAST:event_buttonRecomendarActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        carta1.setRank(carta1.getRank((String)numero1.getSelectedItem()));
        updateLabel (carta1,labelImagen1);
        return;
    }//GEN-LAST:event_numero1ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
    	  carta2.setRank(carta2.getRank((String)numero2.getSelectedItem()));
        updateLabel (carta2,labelImagen2);
        return;
    }//GEN-LAST:event_numero2ActionPerformed

    private static final String IMAGE_PATH_FORMAT = "/images/card_%s.png"; 
    
    protected void updateLabel(Card carta,JLabel picture) {
    	
        ImageIcon icon = ResourceManager.getCardImage(carta);//createImageIcon("images/" + carta.toString() + ".gif");
     
        picture.setIcon(icon);
        if (icon != null) {
            picture.setText(null);
        } else {
            picture.setText("Image not found");
        }
    }
        
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = Principal.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRecomendar;
    private javax.swing.JSpinner fichasApostadasJugador;
    private javax.swing.JSpinner fichasApostadasOponente;
    private javax.swing.JSpinner fichasJugador;
    private javax.swing.JSpinner fichasOponente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label labelApostadas1;
    private java.awt.Label labelApostadas2;
    private java.awt.Label labelCartas;
    private java.awt.Label labelFichas1;
    private java.awt.Label labelFichas2;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JLabel labelImagen2;
    private java.awt.Label labelJugador1;
    private java.awt.Label labelJugador2;
    private javax.swing.JCheckBox luzGrande;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuItemReiniciar;
    private javax.swing.JComboBox numero1;
    private javax.swing.JComboBox numero2;
    private javax.swing.JComboBox palo1;
    private javax.swing.JComboBox palo2;
    private javax.swing.JComboBox personalidadOponente;
    // End of variables declaration//GEN-END:variables
}
