#created on: 19-jun-2011
package fi.uba.drools.poker
import fi.uba.drools.poker.models.Player
import fi.uba.drools.poker.models.Hand
import fi.uba.drools.poker.models.Action
import fi.uba.drools.poker.models.Table
import fi.uba.drools.poker.models.Decision
import java.util.Random
import fi.uba.drools.poker.utils.Constants
#list any import classes here.



#declare any global variables here
#REGLAS PARA BIG BLIND

rule "Regla # 1 Soy luz grande, oponente hizo call y mi mano esta en el TOP 30%"
 when
  $table : Table( mainPlayer.rankHand  < 30 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  $table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  System.out.println("Aplico Regla # 1");
end

rule "Regla # 2 Soy luz grande, oponente hizo call y mi mano esta entre TOP 30% - 40%"
 when
  $table : Table( (mainPlayer.rankHand  == 30 || mainPlayer.rankHand  == 40) && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  //TODO obtener tamaño del pozo
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	if(num <= 60){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		//TODO falta decirle cuanto raisear
  	}  		
  	else if(num >60){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	}  	
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 80){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		
  	}  		
  	else if(num >80){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
  }
  System.out.println("Aplico Regla # 2");
end

rule "Aplico Regla # 3 Soy luz grande, oponente hizo call y mi mano esta en el TOP 50%"
 when
  $table : Table( mainPlayer.rankHand  == 50 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	if(num <= 60){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		//TODO falta decirle cuanto raisear
  	}  		
  	else if(num >60){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	}  	
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 50){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		//TODO falta decirle cuanto raisear
  	}  		
  	else if(num >50){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
  }
  System.out.println("Aplico Regla # 3");
end

rule "Regla # 4 Soy luz grande, oponente hizo call y mi mano esta entre TOP >50% - 100%"
 when
  $table : Table( mainPlayer.rankHand  > 50 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  $table.mainPlayer.setDecision(new Decision(Action.CHECK,0));
   System.out.println("Aplico Regla # 4");
end


rule "Regla # 5 Soy luz grande, oponente hizo raise y mi mano esta entre TOP 5% - 20%"
 when
  $table : Table( mainPlayer.rankHand  <= 20 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  //NO IMPORTA LA AGRESIVIDAD DE MI OPONENTE, SIEMPRE HAGO RAISE
  int potSize = $table.getPotSize();
  int bigBlind = $table.bigBlind;
  int openentRaise = $table.opponentPlayer.getDecision().getBetsize();
  int openentRaiseInBB = openentRaise / bigBlind; 
  int rank = $table.mainPlayer.getRankHand();
  
   System.out.println("el pozo es: "+potSize);
   System.out.println("bigBlind es: "+bigBlind);
   System.out.println("openentRaise es: "+openentRaise);  
   System.out.println("openentRaiseInBB es: "+openentRaiseInBB);
     
    if(rank == 5){
  	
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  		if( openentRaiseInBB <= 20 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  20 < openentRaiseInBB ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		}  	  	
  	}
  
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  		if( openentRaiseInBB <= 12 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  12 < openentRaiseInBB && openentRaiseInBB < 22 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	}  		
  }
   if(rank == 10){
  	
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  		if( openentRaiseInBB <= 15 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  15 < openentRaiseInBB && openentRaiseInBB < 25 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	  	
  	}
  
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  		if( openentRaiseInBB <= 12 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  12 < openentRaiseInBB && openentRaiseInBB < 22 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	}  		
  }
  if(rank == 15){
  	
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  		if( openentRaiseInBB <= 6 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  6 < openentRaiseInBB && openentRaiseInBB < 15 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	  	
  	}
  
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  		if( openentRaiseInBB <= 4 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  4 < openentRaiseInBB && openentRaiseInBB < 10 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	}  		
  }
  if(rank == 20){
  	
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  		if( openentRaiseInBB <= 4 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  4 < openentRaiseInBB && openentRaiseInBB < 12 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	  	
  	}
  
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  		if( openentRaiseInBB <= 3 ){
 			$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize)); //TODO analizar bien cuanto subir 			
  		}
  		else if(  3 < openentRaiseInBB && openentRaiseInBB < 10 ){
 			$table.mainPlayer.setDecision(new Decision(Action.CALL,0)); 			
  		} 
  		else{
  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  		}
  	}  		
  } 
  
  
   System.out.println("Aplico Regla # 5");
end

rule "Regla # 6 Soy luz grande, oponente hizo raise y mi mano esta entre TOP 30%"
 when
  $table : Table( mainPlayer.rankHand  == 30 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then 
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
 
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize + 2*potSize/10));
  	  	
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  		if(num <= 60){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize + 2*potSize/10));
  		
  	}  		
  	else if(num >60){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
   }
   System.out.println("Aplico Regla # 6");
end

rule "Regla # 7 Soy luz grande, oponente hizo raise y mi mano esta entre TOP 40% - 60%"
 when
  $table : Table( (mainPlayer.rankHand == 40 || mainPlayer.rankHand == 50 || mainPlayer.rankHand == 60) && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then
  int openentRaise = $table.opponentPlayer.getDecision().getBetsize(); 
  Random random = new Random();
  int num = random.nextInt(100);
  
  if(openentRaise == 2*$table.bigBlind){//si subio 2BB
  	
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if(num <= 60){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 4*$table.bigBlind + $table.bigBlind/2 ));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >60){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}  	
	  }
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if(num <= 40){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 4*$table.bigBlind + $table.bigBlind/2));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 
	  }
	  
  }
 else if(openentRaise == 2*$table.bigBlind + $table.bigBlind/2 ){//si subio 2,5BB
  		
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if(num <= 70){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 5*$table.bigBlind));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >70){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}  	
	  }
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if(num <= 50){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 5*$table.bigBlind));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 
	  }
	  
  }
  else{
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
  System.out.println("Aplico Regla # 7");
end

rule "Regla # 8 Soy luz grande, oponente hizo raise y mi mano esta entre TOP 70% - 80%"
 when
  $table : Table( (mainPlayer.rankHand == 70 || mainPlayer.rankHand == 80 ) && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then
  int openentRaise = $table.opponentPlayer.getDecision().getBetsize() / $table.bigBlind; //convierto la apuesta del oponente en numero de luces 
  if(openentRaise == 2*$table.bigBlind ){//si subio a 2BB
  	
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	 
	 }
	Random random = new Random();
  	int num = random.nextInt(100);
	
	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if(num <= 90){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		
	  	}  		
	  	else if(num >90){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}  	
	  }  
  }
  else{
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
  System.out.println("Aplico Regla # 8");
end

rule "Regla # 9 Soy luz grande, oponente hizo raise y mi mano esta entre TOP 90% - 100%"
 when
  $table : Table( mainPlayer.rankHand  >= 90 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
   System.out.println("Aplico Regla # 9");
end


rule "REGLA 10 --> Soy luz grande, oponente hizo call, hice raise (mi mano esta en el TOP <30%) y el oponente hizo re raise"
 when
  $table : Table( mainPlayer.rankHand  < 30 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.RE_RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if( rank == 20){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}
	  	else if (rank == 15){
	  		if(potSize/openentReRaise > 2){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 10 || rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  	}
	  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	if( rank == 20){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	  	
	  	else if (rank == 15 || rank == 10 || rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  	}
	  	  	
	 }
      System.out.println("Aplico Regla # 10");
end


rule "REGLA 11 --> Soy luz grande, oponente hizo call, hice raise (mi mano esta en el TOP <30%) y el oponente hizo ALL IN"
 when
  $table : Table( mainPlayer.rankHand  < 30 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	 if( rank == 20){
	  		if( m < 10 || relationPotAndStack>40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 15){
	  		if( m < 10 || relationPotAndStack>=30){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	
	  	else if (rank == 10 || rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 		  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	 if( rank == 20){
	  		if( m < 10 || relationPotAndStack>30){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 15){
	  		if( m < 12 || relationPotAndStack>=30){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	
	  	else if (rank == 10 || rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 	
	 }
      System.out.println("Aplico Regla # 11");
end

rule "REGLA 12 --> Soy luz grande, oponente hizo call, hice raise (mi mano esta en el TOP 30%-40%) y el oponente hizo re raise"
 when
  $table : Table( (mainPlayer.rankHand  == 30 || mainPlayer.rankHand  == 40) && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.RE_RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int myBet = $table.mainPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int bigBlind = $table.bigBlind;
  int diferenceInBB = (openentReRaise - myBet) / bigBlind; 
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if( rank == 40){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}
	  	else if (rank == 30){
	  		if(potSize/openentReRaise > 2 || diferenceInBB <= 10){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	if( rank == 40){
	 		if(potSize/openentReRaise >3 || diferenceInBB <= 10){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	
	  	else if (rank == 30){
	  		if(potSize/openentReRaise > 2 || diferenceInBB <= 12){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	  	
	 }
      System.out.println("Aplico Regla # 12");
end

rule "REGLA 13 --> Soy luz grande, oponente hizo call, hice raise (mi mano esta en el TOP 30%-40%) y el oponente hizo ALL IN"
 when
  $table : Table( (mainPlayer.rankHand  == 30 || mainPlayer.rankHand  == 40) && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	 if( rank == 30){
	  		if( m < 10 || relationPotAndStack>=50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 40){
	  		if( m < 10 || relationPotAndStack>=60){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	 		  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	 if( rank == 30){
	  		if( m < 10 || relationPotAndStack>=40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 40){
	  		if( m < 12 || relationPotAndStack>=50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	 }
      System.out.println("Aplico Regla # 13");
end

rule "REGLA 14 --> Soy luz grande, oponente hizo call, hice raise (mi mano esta en el TOP 50%) y el oponente hizo re raise"
 when
  $table : Table( mainPlayer.rankHand  == 50 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.RE_RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	 $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	 }
  else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	 }
      System.out.println("Aplico Regla # 14");
end



rule "REGLA 15 --> Soy luz grande, oponente hizo call, hice raise (mi mano esta en el TOP 50%) y el oponente hizo ALL IN"
 when
  $table : Table( mainPlayer.rankHand  == 50 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	 $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	 }
  else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	 }
      System.out.println("Aplico Regla # 15");
end

rule "REGLA 16 --> Soy luz grande, oponente hizo raise, hice re raise (mi mano esta en el TOP 5% al TOP 20%) y el oponente hizo re raise"
 when
  $table : Table( (mainPlayer.rankHand  == 5 || mainPlayer.rankHand  == 10 || mainPlayer.rankHand  == 15 || mainPlayer.rankHand  == 20) && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RE_RAISE, opponentPlayer.decision.action == Action.RE_RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if( rank == 20){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}
	  	else if (rank == 10 || rank == 15){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		
	  	}
	  	else if (rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.ALL_IN,0));
	  	}
	  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	if( rank == 20){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}
	  	else if (rank == 15){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		
	  	}
	  	else if (rank == 10){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  		
	  	}
	  	else if (rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.ALL_IN,0));
	  	}
	 }
      System.out.println("Aplico Regla # 16");
end


rule "REGLA 17 --> Soy luz grande, oponente hizo raise, hice re raise (mi mano esta en el TOP 5% al TOP 20%) y el oponente hizo all in"
 when
  $table : Table( (mainPlayer.rankHand  == 5 || mainPlayer.rankHand  == 10 || mainPlayer.rankHand  == 15 || mainPlayer.rankHand  == 20) && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RE_RAISE, opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand();
  int relationPotAndStack= potSize*100/playerStack; 
  int m = playerStack/ $table.getBigBlind();
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if( rank == 20){
	  		if ( m < 8 || relationPotAndStack>=50){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 15){
	  		if ( m < 10 || relationPotAndStack>=40){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 10){
	  		if ( m < 10 || relationPotAndStack>=30){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}  		
	  	}
	  	else if (rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}	  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	if( rank == 20){
	  		if ( m < 8 || relationPotAndStack>=50){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 15){
	  		if ( m < 10 || relationPotAndStack>=40){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 10){
	  		if ( m < 10 || relationPotAndStack>=30){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}  		
	  	}
	  	else if (rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	 }
      System.out.println("Aplico Regla # 17");
end

rule "Regla # 18 Soy luz grande, oponente hizo raise, hice re raise (mi mano esta en el TOP 30%) y el oponente hizo re raise"
 when
  $table : Table( mainPlayer.rankHand  == 30 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RE_RAISE, opponentPlayer.decision.action == Action.RE_RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int relationPotAndStack= potSize*100/playerStack; 
  int m = playerStack/ $table.getBigBlind();
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  if ( m < 6 || relationPotAndStack>=50){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	  else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	} 	  
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 if ( m < 8 || relationPotAndStack>=45){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	 else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
		} 
	 }
      System.out.println("Aplico Regla # 18");
end

rule "REGLA 19 --> Soy luz grande, oponente hizo raise, hice re raise (mi mano esta en el TOP 30%) y el oponente hizo all in"
 when
  $table : Table( mainPlayer.rankHand == 30 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RE_RAISE, opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand();
  int relationPotAndStack= potSize*100/playerStack; 
  int m = playerStack/ $table.getBigBlind();
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  if ( m < 7 || relationPotAndStack>=50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}	 
	  else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}  
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 if ( m < 9  || relationPotAndStack>=45){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	 else{
	 		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	} 
	 }      
	 System.out.println("Aplico Regla # 19");
end


rule "REGLA 20 --> Soy luz grande, oponente hizo raise, hice re raise (mi mano esta en el TOP 40%-60%) y el oponente hizo re raise o all in"
 when
  $table : Table( (mainPlayer.rankHand == 40 || mainPlayer.rankHand  == 50 || mainPlayer.rankHand  == 60) && mainPlayer.position  ==  Constants.Blind.BIG_BLIND && mainPlayer.decision.action == Action.RE_RAISE, opponentPlayer.decision.action == Action.RE_RAISE || opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
  
  if ( potOdds >= 3 && rank == 40 ){
  	$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  }
  else{
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }

      System.out.println("Aplico Regla # 20");
end


#FIN REGLAS PARA BIG BLIND

#REGLAS PARA SMALL BLIND o BUTTON
rule "REGLA 21 --> Soy boton y mi mano esta en el TOP 50%, me toca apostar, mi oponente todavia no hablo"
 when
  $table : Table( mainPlayer.rankHand  <= 50 && mainPlayer.position == Constants.Blind.SMALL_BLIND && opponentPlayer.decision.action == Action.CONTINUE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  Random random = new Random();
  int num = random.nextInt(100);
  
  if(num <= 80){
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	$table.mainPlayer.setDecision(new Decision(Action.BET,3*$table.bigBlind));
	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	$table.mainPlayer.setDecision(new Decision(Action.BET,3*$table.bigBlind));
	  	  	
	 }
  
   }
  else if( num >80){
  	$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  
  }    
  System.out.println("Aplico Regla # 21");
end


rule "REGLA 22 --> Soy boton y mi mano esta en el TOP 60% - 80%"
 when
  $table : Table( (mainPlayer.rankHand  == 60 || mainPlayer.rankHand  == 70 || mainPlayer.rankHand  == 80) && mainPlayer.position == Constants.Blind.SMALL_BLIND && opponentPlayer.decision.action == Action.CONTINUE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	if(num <= 25){
  		$table.mainPlayer.setDecision(new Decision(Action.BET, 2*$table.bigBlind + $table.bigBlind/2));
  	}  		
  	else if(num >25 && num <= 50){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	}  	
  	else if(num > 50){
  	  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  	}
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 40){
  		$table.mainPlayer.setDecision(new Decision(Action.BET, 2*$table.bigBlind));
  		
  	}  		
  	else if(num >40){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
  }  
  System.out.println("Aplico Regla # 22");
end


rule "REGLA 23 --> Soy boton y mi mano esta entre TOP 90% - 100%"
 when
  $table : Table( (mainPlayer.rankHand  == 90 || mainPlayer.rankHand  == 100) && mainPlayer.position == Constants.Blind.SMALL_BLIND && opponentPlayer.decision.action == Action.CONTINUE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  Random random = new Random();
  int num = random.nextInt(100);
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 20){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  		
  	}  		
  	else if(num >20){
  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  	} 
  }
   System.out.println("Aplico Regla # 23");
end

rule "REGLA 24 --> Soy boton, hice raise (mi mano esta en el TOP <=50%) y el oponente hizo re raise"
 when
  $table : Table( mainPlayer.rankHand  <= 50 && mainPlayer.position  ==  Constants.Blind.SMALL_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.RE_RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if( rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  	}	  	
	  	else if (rank == 10){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  	}
	  	else if (rank == 15){
	  		if(relationPotAndStack <=20){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 20 || rank == 30){
	  		if(potOdds >=2 && relationPotAndStack <=10){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 40){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}
	  	else if (rank == 50){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}	  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if( rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  	}	  	
	  	else if (rank == 10){
	  		$table.mainPlayer.setDecision(new Decision(Action.RE_RAISE,potSize+ 3*potSize/10));
	  	}
	  	else if (rank == 15 || rank == 20 || rank == 30){
	  		if(potOdds >=1 && relationPotAndStack <=20 ){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if (rank == 40){
	  		if(potOdds >=2){
	  			$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  			$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}	  	
	  	else if (rank == 50){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	}	  	  	 	  	  	
	 }
      System.out.println("Aplico Regla # 24");
end


rule "REGLA 25 --> Soy boton, hice raise (mi mano esta en el TOP <=50%) y el oponente hizo ALL IN"
 when
  $table : Table( mainPlayer.rankHand  <= 50 && mainPlayer.position  ==  Constants.Blind.SMALL_BLIND && mainPlayer.decision.action == Action.RAISE, opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
 
 if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	   if( rank == 50){
	  		if( m < 6 || relationPotAndStack>70){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 40){
	  		if( m < 8 || relationPotAndStack>60){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	 else if( rank == 30){
	  		if( m < 10 || relationPotAndStack>50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	 else if( rank == 20){
	  		if( m < 12 || relationPotAndStack>40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 15){
	  		if( m < 10 || relationPotAndStack>=30){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	
	  	else if (rank == 10){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	  	else if (rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 		  	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	   if( rank == 50){
	  		if( m < 6 || relationPotAndStack>60){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 40){
	  		if( m < 8 || relationPotAndStack>50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	 else if( rank == 30){
	  		if( m < 10 || relationPotAndStack>40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	 else if( rank == 20){
	  		if( m < 12 || relationPotAndStack>40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	else if( rank == 15){
	  		if( m < 10 || relationPotAndStack>=30){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  		}
	  		else{
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		}
	  	}
	  	
	  	else if (rank == 10){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}
	  	else if (rank == 5){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 	
	 }
      System.out.println("Aplico Regla #25");
end

rule "REGLA 26 --> Soy boton, hice raise o call (mi mano esta en el TOP 60%-80%) y el oponente hizo re raise o all in"
 when
  $table : Table( (mainPlayer.rankHand == 60 || mainPlayer.rankHand  == 70 || mainPlayer.rankHand  == 80) && mainPlayer.position  ==  Constants.Blind.SMALL_BLIND && (mainPlayer.decision.action == Action.RAISE || mainPlayer.decision.action == Action.CALL) && (opponentPlayer.decision.action == Action.RE_RAISE || opponentPlayer.decision.action == Action.ALL_IN))
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  int openentReRaise = $table.opponentPlayer.getDecision().getBetsize();
  int playerStack = $table.mainPlayer.getCash();
  int playerBet = $table.mainPlayer.getBet();
  int rank = $table.mainPlayer.getRankHand(); 
  int potOdds = potSize/openentReRaise;
  int m = playerStack/ $table.getBigBlind();
  int relationPotAndStack= potSize*100/playerStack;
  
  if ( potOdds >= 3 && rank == 60){
  	$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  }
  else{
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
System.out.println("Aplico Regla # 26");
      
end

rule "REGLA 27 --> Soy boton, hice call (mi mano esta en el TOP 90%-100%) y el oponente hizo raise o all in"
 when
  $table : Table( (mainPlayer.rankHand == 90 || mainPlayer.rankHand  == 100) && mainPlayer.position  ==  Constants.Blind.SMALL_BLIND && mainPlayer.decision.action == Action.CALL, opponentPlayer.decision.action == Action.RAISE || opponentPlayer.decision.action == Action.ALL_IN)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
 $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
       System.out.println("Aplico Regla # 27");
end

#FIN PARA SMALL BLIND o BUTTON
