#created on: 19-jun-2011
package fi.uba.drools.poker
import fi.uba.drools.poker.models.Player
import fi.uba.drools.poker.models.Hand
import fi.uba.drools.poker.models.Action
import fi.uba.drools.poker.models.Table
import fi.uba.drools.poker.models.Decision
import java.util.Random
import fi.uba.drools.poker.utils.Constants
#list any import classes here.



#declare any global variables here
#REGLAS PARA BIG BLIND

rule "Soy luz grande, oponente hizo call y mi mano esta en el TOP 30%"
 when
  $table : Table( mainPlayer.rankHand  < 30 && mainPlayer.position  ==  Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  $table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
end

rule "Soy luz grande, oponente hizo call y mi mano esta entre TOP 30% - 40%"
 when
  $table : Table( (mainPlayer.rankHand  == 30 || mainPlayer.rankHand  == 40) && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  //TODO obtener tamaño del pozo
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	if(num <= 60){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		//TODO falta decirle cuanto raisear
  	}  		
  	else if(num >60){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	}  	
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 80){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		
  	}  		
  	else if(num >80){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
  }
  
end

rule "Soy luz grande, oponente hizo call y mi mano esta en el TOP 50%"
 when
  $table : Table( mainPlayer.rankHand  == 50 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	if(num <= 60){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		//TODO falta decirle cuanto raisear
  	}  		
  	else if(num >60){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	}  	
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 50){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, potSize + 5*potSize/10));
  		//TODO falta decirle cuanto raisear
  	}  		
  	else if(num >50){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
  }
  
end

rule "Soy luz grande, oponente hizo call y mi mano esta entre TOP >50% - 100%"
 when
  $table : Table( mainPlayer.rankHand  > 50 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.CALL)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  $table.mainPlayer.setDecision(new Decision(Action.CHECK,0));
   
end


rule "Soy luz grande, oponente hizo raise y mi mano esta entre TOP 5% - 20%"
 when
  $table : Table( mainPlayer.rankHand  <= 20 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  //NO IMPORTA LA AGRESIVIDAD DE MI OPONENTE, SIEMPRE HAGO RAISE
  int potSize = $table.getPotSize();
  $table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize + potSize/2)); //TODO analizar bien cuanto subir
   
end

rule "Soy luz grande, oponente hizo raise y mi mano esta entre TOP 30%"
 when
  $table : Table( mainPlayer.rankHand  == 30 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then 
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
 
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize + 2*potSize/10));
  	  	
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  		if(num <= 60){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*potSize + 2*potSize/10));
  		
  	}  		
  	else if(num >60){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
   }
   
end

rule "Soy luz grande, oponente hizo raise y mi mano esta entre TOP 40% - 60%"
 when
  $table : Table( (mainPlayer.rankHand == 40 || mainPlayer.rankHand == 50 || mainPlayer.rankHand == 60) && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then
  int openentRaise = $table.opponentPlayer.getDecision().getBetsize(); 
  Random random = new Random();
  int num = random.nextInt(100);
  
  if(openentRaise == 2*$table.bigBlind){//si subio 2BB
  	
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if(num <= 60){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 4*$table.bigBlind + $table.bigBlind/2 ));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >60){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}  	
	  }
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if(num <= 40){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 4*$table.bigBlind + $table.bigBlind/2));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >40){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 
	  }
	  
  }
 else if(openentRaise == 2*$table.bigBlind + $table.bigBlind/2 ){//si subio 2,5BB
  		
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if(num <= 70){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 5*$table.bigBlind));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >70){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}  	
	  }
	  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	if(num <= 50){
	  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 5*$table.bigBlind));
	  		//TODO falta decirle cuanto raisear
	  	}  		
	  	else if(num >50){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	} 
	  }
	  
  }
  else{
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
  
end

rule "Soy luz grande, oponente hizo raise y mi mano esta entre TOP 70% - 80%"
 when
  $table : Table( (mainPlayer.rankHand == 70 || mainPlayer.rankHand == 80 ) && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then
  int openentRaise = $table.opponentPlayer.getDecision().getBetsize() / $table.bigBlind; //convierto la apuesta del oponente en numero de luces 
  if(openentRaise == 2*$table.bigBlind ){//si subio a 2BB
  	
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  	 
	 }
	Random random = new Random();
  	int num = random.nextInt(100);
	
	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	  	if(num <= 90){
	  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
	  		
	  	}  		
	  	else if(num >90){
	  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
	  	}  	
	  }  
  }
  else{
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
end

rule "Soy luz grande, oponente hizo raise y mi mano esta entre TOP 90% - 100%"
 when
  $table : Table( mainPlayer.rankHand  >= 90 && mainPlayer.position  == Constants.Blind.BIG_BLIND, opponentPlayer.decision.action == Action.RAISE)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  $table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
   
end
#FIN REGLAS PARA BIG BLIND

#REGLAS PARA SMALL BLIND o BUTTON
rule "Soy boton y mi mano esta en el TOP 50%"
 when
  $table : Table( mainPlayer.rankHand  <= 50 && mainPlayer.position == Constants.Blind.SMALL_BLIND)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  Random random = new Random();
  int num = random.nextInt(100);
  
  if(num <= 80){
  	if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
	  	$table.mainPlayer.setDecision(new Decision(Action.RAISE,3*$table.bigBlind));
	  	 
	 }
	else if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
	 	$table.mainPlayer.setDecision(new Decision(Action.RAISE,3*$table.bigBlind));
	  	  	
	 }
  
   }
  else if( num >80){
  	$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  
  }    
end


rule "Soy boton y mi mano esta en el TOP 60% - 80%"
 when
  $table : Table( (mainPlayer.rankHand  == 60 || mainPlayer.rankHand  == 70 || mainPlayer.rankHand  == 80) && mainPlayer.position == Constants.Blind.SMALL_BLIND)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  int potSize = $table.getPotSize();
  Random random = new Random();
  int num = random.nextInt(100);
  
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	if(num <= 25){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*$table.bigBlind + $table.bigBlind/2));
  	}  		
  	else if(num >25 && num <= 50){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	}  	
  	else if(num > 50){
  	  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  	}
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 40){
  		$table.mainPlayer.setDecision(new Decision(Action.RAISE, 2*$table.bigBlind));
  		
  	}  		
  	else if(num >40){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  	} 
  }  
end


rule "Soy boton y mi mano esta entre TOP 90% - 100%"
 when
  $table : Table( (mainPlayer.rankHand  == 90 || mainPlayer.rankHand  == 100) && mainPlayer.position == Constants.Blind.SMALL_BLIND)
  
 then 
  #  System.out.println("Mi posicion es "+mainPlayer.getPosition()+" ,mi mano es "+mainPlayer.getHand().toString()+".");
  Random random = new Random();
  int num = random.nextInt(100);
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.AGGRESIVE)){
  	$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  }
  if($table.opponentPlayer.getStrategy().equals(Constants.Strategy.TIGHT)){
  	if(num <= 20){
  		$table.mainPlayer.setDecision(new Decision(Action.CALL,0));
  		
  	}  		
  	else if(num >20){
  		$table.mainPlayer.setDecision(new Decision(Action.FOLD,0));
  	} 
  }
   
end
#FIN PARA SMALL BLIND o BUTTON
